/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CleanerRouteImport } from './routes/cleaner'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminCasesCaseIdRouteImport } from './routes/admin.cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerRoute = CleanerRouteImport.update({
  id: '/cleaner',
  path: '/cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesCaseIdRoute = AdminCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cleaner': typeof CleanerRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/track': typeof TrackRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cleaner': typeof CleanerRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/track': typeof TrackRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cleaner': typeof CleanerRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRoute
  '/track': typeof TrackRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cleaner'
    | '/guide'
    | '/login'
    | '/submit'
    | '/track'
    | '/admin/knowledge'
    | '/admin/verification'
    | '/admin/'
    | '/admin/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cleaner'
    | '/guide'
    | '/login'
    | '/submit'
    | '/track'
    | '/admin/knowledge'
    | '/admin/verification'
    | '/admin'
    | '/admin/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cleaner'
    | '/guide'
    | '/login'
    | '/submit'
    | '/track'
    | '/admin/knowledge'
    | '/admin/verification'
    | '/admin/'
    | '/admin/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CleanerRoute: typeof CleanerRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  SubmitRoute: typeof SubmitRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner': {
      id: '/cleaner'
      path: '/cleaner'
      fullPath: '/cleaner'
      preLoaderRoute: typeof CleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases/$caseId': {
      id: '/admin/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/admin/cases/$caseId'
      preLoaderRoute: typeof AdminCasesCaseIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCasesCaseIdRoute: typeof AdminCasesCaseIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCasesCaseIdRoute: AdminCasesCaseIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CleanerRoute: CleanerRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  SubmitRoute: SubmitRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
