/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CleanerRouteImport } from './routes/cleaner'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as CleanerIndexRouteImport } from './routes/cleaner.index'
import { Route as AdminCasesCaseIdRouteImport } from './routes/admin.cases.$caseId'
import { Route as CleanerTasksTaskIdRouteImport } from './routes/cleaner.tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerRoute = CleanerRouteImport.update({
  id: '/cleaner',
  path: '/cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const CleanerIndexRoute = CleanerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CleanerRoute,
} as any)
const AdminCasesCaseIdRoute = AdminCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AdminRoute,
} as any)
const CleanerTasksTaskIdRoute = CleanerTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => CleanerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cleaner': typeof CleanerRouteWithChildren
  '/submit': typeof SubmitRoute
  '/track': typeof TrackRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/': typeof AdminIndexRoute
  '/cleaner/': typeof CleanerIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
  '/cleaner/tasks/$taskId': typeof CleanerTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/submit': typeof SubmitRoute
  '/track': typeof TrackRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin': typeof AdminIndexRoute
  '/cleaner': typeof CleanerIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
  '/cleaner/tasks/$taskId': typeof CleanerTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cleaner': typeof CleanerRouteWithChildren
  '/submit': typeof SubmitRoute
  '/track': typeof TrackRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/': typeof AdminIndexRoute
  '/cleaner/': typeof CleanerIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
  '/cleaner/tasks/$taskId': typeof CleanerTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cleaner'
    | '/submit'
    | '/track'
    | '/admin/events'
    | '/admin/'
    | '/cleaner/'
    | '/admin/cases/$caseId'
    | '/cleaner/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/submit'
    | '/track'
    | '/admin/events'
    | '/admin'
    | '/cleaner'
    | '/admin/cases/$caseId'
    | '/cleaner/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cleaner'
    | '/submit'
    | '/track'
    | '/admin/events'
    | '/admin/'
    | '/cleaner/'
    | '/admin/cases/$caseId'
    | '/cleaner/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CleanerRoute: typeof CleanerRouteWithChildren
  SubmitRoute: typeof SubmitRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner': {
      id: '/cleaner'
      path: '/cleaner'
      fullPath: '/cleaner'
      preLoaderRoute: typeof CleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cleaner/': {
      id: '/cleaner/'
      path: '/'
      fullPath: '/cleaner/'
      preLoaderRoute: typeof CleanerIndexRouteImport
      parentRoute: typeof CleanerRoute
    }
    '/admin/cases/$caseId': {
      id: '/admin/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/admin/cases/$caseId'
      preLoaderRoute: typeof AdminCasesCaseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cleaner/tasks/$taskId': {
      id: '/cleaner/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/cleaner/tasks/$taskId'
      preLoaderRoute: typeof CleanerTasksTaskIdRouteImport
      parentRoute: typeof CleanerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCasesCaseIdRoute: typeof AdminCasesCaseIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCasesCaseIdRoute: AdminCasesCaseIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CleanerRouteChildren {
  CleanerIndexRoute: typeof CleanerIndexRoute
  CleanerTasksTaskIdRoute: typeof CleanerTasksTaskIdRoute
}

const CleanerRouteChildren: CleanerRouteChildren = {
  CleanerIndexRoute: CleanerIndexRoute,
  CleanerTasksTaskIdRoute: CleanerTasksTaskIdRoute,
}

const CleanerRouteWithChildren =
  CleanerRoute._addFileChildren(CleanerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CleanerRoute: CleanerRouteWithChildren,
  SubmitRoute: SubmitRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
